version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - .:/app     # 👈 mount the whole project root
    working_dir: /app/server
    command: sh -c "npm install && npx nodemon server.js"
    
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
