version: "3.8"
services:
  app:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - .:/app     # 👈 mount the whole project root
    working_dir: /app/server
    command: sh -c "cd /app/client && npm install && npm run build && cd /app/server && npm install && npx nodemon server.js"
